dist: trusty
sudo: false

addons:
  chrome: stable

language: node_js
node_js:
  - "node"

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  # use Chromium instead of Chrome
  - export CHROME_BIN=chromium-browser

script:
  # run linters
  - yarn lint:ng
  - yarn lint:css
  - yarn lint:prettier
  - yarn lint:sort

  # run unit tests
  - xvfb-run -a yarn test --code-coverage --single-run --no-progress --browser=ChromeNoSandbox

  # send coverage info
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage

  # run e2e tests
  - xvfb-run -a yarn e2e --no-progress --config=protractor-ci.conf.js

before_deploy:
  # install now
  - yarn global install now

deploy:
  - provider: script
    skip_cleanup: true
    script: ./scripts/deploy.sh $TRAVIS_BRANCH
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^master|develop$
