dist: trusty
sudo: required
language: node_js
node_js:
  - "7"

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - npm config set spin false
  - npm config set progress false

install:
  - npm install --no-optional

before_script:
  - npm start &
  - sleep 20

script:
  - npm run lint
  - npm run test:ci
  - npm run e2e
