dist: trusty
sudo: false

language: node_js
node_js:
  - node

cache:
  directories:
     - ./node_modules

before_install: if [[ `npm -v` != 5.3.0* ]]; then npm i -g npm@5.3.0; fi

before_script:
  # ssh setup
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # use Chromium instead of Chrome
  - export CHROME_BIN=chromium-browser

script:
  # run linters
  - npm run lint:ng
  - npm run lint:css
  - npm run lint:prettier
  - npm run lint:sort

  # run unit tests
  - xvfb-run -a npm run test -- --code-coverage --single-run --no-progress --browser=ChromeNoSandbox

  # send coverage info
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage

  # run e2e tests
  - xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js

before_deploy:
  # ssh certificates
  - openssl aes-256-cbc -K $encrypted_cf9fe38ad62a_key -iv $encrypted_cf9fe38ad62a_iv -in ./scripts/deploy_key.enc -out deploy_key.pem -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_key.pem
  - ssh-add deploy_key.pem

deploy:
  - provider: script
    skip_cleanup: true
    script: ./scripts/deploy.sh $TRAVIS_BRANCH
    on:
      all_branches: true
